language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t QuantStats/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true QuantStats/docker-react npm run test
